=== AMartin1987/actividades1-UT4/Ej01_Equipos/liga.dtd
<!ELEMENT liga (equipo+)>
<!ELEMENT equipo (nombre_equipo, ubicacion, entrenador, plantel)>
<!ELEMENT nombre_equipo (#PCDATA)>
<!ELEMENT ubicacion (#PCDATA)>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT plantel (jugador+)>
<!ELEMENT jugador (nombres, apellidos, año_nacimiento, lugar_nacimiento, posicion, estatura, peso)>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT año_nacimiento (#PCDATA)>
<!ELEMENT lugar_nacimiento (#PCDATA)>
<!ELEMENT posicion (Portero | Defensor | Centrocampista | Delantero)>
<!ELEMENT estatura (#PCDATA)>
<!ELEMENT peso (#PCDATA)>

=== AMartin1987/actividades1-UT4/Ej01_Equipos/Ej01_Equipos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "Ej01_Equipos\liga.dtd">

<liga>
    <equipo>
        <nombre_equipo>Club Atlético de Madrid</nombre_equipo>
        <ubicacion>Madrid</ubicacion>
        <entrenador>Diego Simeone</entrenador>
        <plantel>
            <jugador>
                <nombres>Julián</nombres>
                <apellidos>Álvarez</apellidos>
                <año_nacimiento>2000</año_nacimiento>
                <lugar_nacimiento>Calchín, Argentina</lugar_nacimiento>
                <posicion>Delantero</posicion>
                <estatura>170</estatura>
                <peso>71</peso>
            </jugador>
            <jugador>
                <nombres>Rodrigo</nombres>
                <apellidos>De Paul</apellidos>
                <año_nacimiento>1994</año_nacimiento>
                <lugar_nacimiento>Sarandí, Argentina</lugar_nacimiento>
                <posicion>Centrocampista</posicion>
                <estatura>180</estatura>
                <peso>70</peso>
            </jugador>
            <jugador>
                <nombres>Ángel Martín</nombres>
                <apellidos>Correa Martínez</apellidos>
                <año_nacimiento>1995</año_nacimiento>
                <lugar_nacimiento>Rosario, Argentina</lugar_nacimiento>
                <posicion>Delantero</posicion>
                <estatura>171</estatura>
                <peso>70</peso>
            </jugador>
            <jugador>
                <nombres>Nahuel</nombres>
                <apellidos>Molina Lucero</apellidos>
                <año_nacimiento>1998</año_nacimiento>
                <lugar_nacimiento>Embalse, Argentina</lugar_nacimiento>
                <posicion>Defensor</posicion>
                <estatura>175</estatura>
                <peso>70</peso>
            </jugador>
            <jugador>
                <nombres>Giuliano</nombres>
                <apellidos>Simeone</apellidos>
                <año_nacimiento>2002</año_nacimiento>
                <lugar_nacimiento>Roma, Italia</lugar_nacimiento>
                <posicion>Delantero</posicion>
                <estatura>173</estatura>
                <peso>75</peso>
            </jugador>
        </plantel>  
    </equipo>
</liga>
