=== AMartin1987/actividades1-UT4/Ej04/caratula_pelicula.dtd
<!ELEMENT caratula_pelicula (imagen_fondo, reparto+, titulo?, descripcion, frase+)>
<!ELEMENT imagen_fondo EMPTY>
<!ATTLIST imagen_fondo src CDATA #REQUIRED>
<!ELEMENT reparto (nombres, apellidos)>
<!ELEMENT nombres (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT descripcion (director)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT frase (#PCDATA)>

=== AMartin1987/actividades1-UT4/Ej04/Ej04.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="Ej04\estilo.css"?>
<!DOCTYPE caratula_pelicula SYSTEM "Ej04\caratula_pelicula.dtd">

<caratula_pelicula>
    <imagen_fondo src="url_de_imagen.jpg">
    </imagen_fondo>
    <reparto>
        <nombres>Ewan</nombres>
        <apellidos>McGregor</apellidos>
    </reparto>
    <titulo>
    </titulo>
    <descripcion>Una pel√≠cula de
        <director>Tim Burton</director>
    </descripcion>
    <frase>Una aventura tan grande como la vida misma
    </frase>
</caratula_pelicula>
