=== AMartin1987/actividades1-UT4/Ej03_CD_Musica/cd_musica.dtd
<!ELEMENT cd (info, lista_temas+)>
<!ELEMENT info (portada?, artista, titulo, sello, referencia, año, pais, formato, genero, estilo, observaciones)>
<!ELEMENT portada EMPTY>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT sello (#PCDATA)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT formato (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT estilo (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT lista_temas (numero, titulo, duracion)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>

=== AMartin1987/actividades1-UT4/Ej03_CD_Musica/Ej03_CD_Musica.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilo.css"?>
<!DOCTYPE liga SYSTEM "cd_musica.dtd">

<cd>
    <info>
        <portada>
        </portada>
        <artista>ABC (2)
        </artista>
        <titulo>The Collection
        </titulo>
        <sello>KARUSSELL INTERNATIONAL
        </sello>
        <referencia>551 831-2
        </referencia>
        <año>1996
        </año>
        <pais>Germany
        </pais>
        <formato>CD - Compilation
        </formato>
        <genero>Funk / Soul, Electronic
        </genero>
        <estilo>Funk Disco, Synth Pop
        </estilo>
        <observaciones>Licenced from Mercury Records Ltd (London)
        </observaciones>
    </info>
    <lista_temas>
        <numero>01</numero>
        <titulo>Poison Arrow</titulo>
        <duracion>[03:23]</duracion>
    </lista_temas>
</cd>
